- platform: rest
  name: "HASS latest"
  resource: https://pypi.python.org/pypi/homeassistant/json
  value_template: '{{ value_json.info.version }}'
  scan_interval: 3600
- platform: command_line
  name: HASS installed
  command: "head -5 /home/homeassistant/.homeassistant/.HA_VERSION"
- platform: systemmonitor 
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: swap_use
  - type: last_boot
  - type: ipv4_address
    arg: eth0
- platform: rest
  resource: !secret smhipathtemp
  name: Temp
  value_template: "{{ value_json.timeSeries[0].parameters[1]['values'][0] }}"
  unit_of_measurement: "°C"
- platform: rest
  resource: !secret smhipathwind
  name: Wind
  value_template: "{{ value_json.timeSeries[0].parameters[4]['values'][0] }}"
  unit_of_measurement: "m/s"
- platform: trafikverket_weatherstation
  name: Trafikverket WeatherStation
  api_key: !secret trafikverket_apikey
  station: !secret trafikverket_station
  monitored_conditions:
      - air_temp
      - road_temp
      - precipitation
      - wind_direction_text
      - wind_speed
